/**
 * @ziioapp/vite-plugin-theme —— 主题系统可拔插 Vite 插件。
 *
 * 工作原理：
 *   1. app 在 ziioapp.theme.ts 里用 defineThemeConfig 声明要哪些主题/底色/图表色。
 *   2. vite.config.ts 把配置对象传给 ziioappTheme(config)。
 *   3. 插件在 configResolved 时根据配置 + 兜底规则拼出 @import 列表，
 *      写到 app 的 src/styles/theme.gen.css（确定性、内容没变不写）。
 *   4. app 的 src/styles/index.css 用 @import "./theme.gen.css" 引用，
 *      Tailwind v4 递归内联那些 @import。
 *
 * 兜底：无配置 / defaults 省略 → indigo 主题 + zinc 底色 + shadcn 默认图表色。
 *
 * 资源引用（themes/bases/charts/styles 的列表项与 defaults 的字段）支持名称、包或本地 CSS：
 *   - "rose"                                    裸名 → @ziioapp/ui/styles/{kind}/{prefix}{name}.css
 *   - { name: "brand", label: "品牌", group: "品牌色", css: "src/styles/brand.css" }
 *   - { package: "@ziioapp/theme-brand", name: "brand" }  包名 → {package}/styles/{kind}/{prefix}{name}.css
 *   主题包需按 ui 同构布局（styles/themes/theme-{name}.css）并 export ./styles/*。
 *
 * custom 路径：相对 app 根解析，插件换算成相对 theme.gen.css 的路径；
 * 包名（@ 开头）/绝对路径/URL 原样透传。
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, isAbsolute, relative, resolve } from "node:path";
import {
  officialBaseColors,
  officialStyles,
  officialThemeColors,
} from "@ziioapp/ui/lib/official-themes";
import type { Plugin } from "vite";

export { officialBaseColors, officialStyles, officialThemeColors };

// ============================================================
// 类型
// ============================================================

/** CSS paths are relative to the application root; scoped package imports and URLs also work. */
export type AssetRef =
  | string
  | {
      name: string;
      label?: string;
      group?: string;
      css?: string;
      package?: string;
    };

export interface ThemeDefaults {
  style?: AssetRef;
  /** 默认主题。省略 → 兜底 "indigo"。 */
  theme?: AssetRef;
  /** 默认底色。省略 → 兜底 "zinc"。 */
  base?: AssetRef;
}

export interface ThemeConfig {
  styles?: readonly AssetRef[];
  /** 默认主题/底色，替换兜底（indigo/zinc）。 */
  defaults?: ThemeDefaults;
  /** 额外打包的主题，供运行时切换。 */
  themes?: readonly AssetRef[];
  /** 额外打包的底色。 */
  bases?: readonly AssetRef[];
  /** 额外打包的图表色板。 */
  charts?: readonly AssetRef[];
  /** app 本地自定义 CSS 路径（相对 app 根）或包名/URL。 */
  custom?: string[];
}

/** 类型 helper，纯做提示，原样返回。 */
export function defineThemeConfig(config: ThemeConfig): ThemeConfig {
  return config;
}

// ============================================================
// 解析
// ============================================================

const RESOURCE_NAME = /^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$/;
const HTTP_URL = /^https?:\/\//;
const DEFAULT_THEME = "indigo";
const DEFAULT_BASE = "zinc";
const GEN_REL_PATH = "src/styles/theme.gen.css";
const HEADER =
  "/* AUTO-GENERATED by @ziioapp/vite-plugin-theme — edit ziioapp.theme.ts instead */";

/** 各分类在 ui 包里的子目录与文件前缀。 */
const KIND_META = {
  themes: { folder: "themes", prefix: "theme-" },
  bases: { folder: "bases", prefix: "base-" },
  charts: { folder: "charts", prefix: "chart-" },
} as const;

type Kind = keyof typeof KIND_META;

/** 把 AssetRef 解析成 @import 路径。 */
function resolveRef(ref: AssetRef, kind: Kind): string {
  const { folder, prefix } = KIND_META[kind];
  if (typeof ref === "string") {
    const official =
      kind === "bases" ? officialBaseColors : officialThemeColors;
    const directory = (official as readonly string[]).includes(ref)
      ? `official/${folder}`
      : folder;
    return `@ziioapp/ui/styles/${directory}/${prefix}${ref}.css`;
  }
  if ("package" in ref && ref.package) {
    return `${ref.package}/styles/${folder}/${prefix}${ref.name}.css`;
  }
  return resolveRef(ref.name, kind);
}

function dedup(arr: string[]): string[] {
  return [...new Set(arr)];
}

/** 从 AssetRef 取主题/底色名（用于运行时清单，对应 .theme-color-{name} 类名）。 */
function resolveName(ref: AssetRef | undefined, fallback: string): string {
  if (!ref) return fallback;
  if (typeof ref === "string") return ref;
  return ref.name;
}

/**
 * 把 custom 路径换算成相对 theme.gen.css 的 @import 路径。
 * - 包名（@ 开头）/绝对路径/URL → 原样透传
 * - 其余 → 视为相对 app 根，换算成相对 gen 文件目录
 */
function resolveCustomPath(p: string, appRoot: string, genDir: string): string {
  if (p.startsWith("@") || p.startsWith("http") || isAbsolute(p)) {
    return p;
  }
  const abs = resolve(appRoot, p);
  let rel = relative(genDir, abs);
  if (!rel.startsWith(".")) rel = `./${rel}`;
  return rel;
}

/** Resolve defaults by name against the registered resources, preserving custom CSS and labels. */
function resources(config: ThemeConfig) {
  function collect(refs: readonly AssetRef[], defaultRef?: AssetRef) {
    const result = new Map<string, AssetRef>();
    for (const ref of [...(defaultRef ? [defaultRef] : []), ...refs]) {
      const name = resolveName(ref, "");
      if (!RESOURCE_NAME.test(name) || name === "base")
        throw new Error(`Invalid or reserved theme resource name: ${name}`);
      if (typeof ref !== "string" && ref.css && ref.package)
        throw new Error(`Choose css or package for theme resource: ${name}`);
      const previous = result.get(name);
      if (previous && typeof previous !== "string" && typeof ref !== "string") {
        if (
          (previous.css && ref.css && previous.css !== ref.css) ||
          (previous.package &&
            ref.package &&
            previous.package !== ref.package) ||
          (previous.css && ref.package) ||
          (previous.package && ref.css)
        )
          throw new Error(`Conflicting theme resource definitions: ${name}`);
        result.set(name, { ...previous, ...ref });
      } else if (!previous || typeof ref !== "string") result.set(name, ref);
    }
    return [...result.values()];
  }
  return {
    styles: collect(
      config.styles ?? officialStyles,
      config.defaults?.style ?? "mira",
    ),
    bases: collect(config.bases ?? [], config.defaults?.base ?? DEFAULT_BASE),
    themes: collect(
      config.themes ?? [],
      config.defaults?.theme ?? DEFAULT_THEME,
    ),
    charts: collect(config.charts ?? []),
  };
}

export function generateImports(config: ThemeConfig, appRoot: string): string {
  const assets = resources(config);
  const genDir = resolve(appRoot, dirname(GEN_REL_PATH));
  function assetPath(ref: AssetRef, kind: Kind | "styles") {
    if (typeof ref !== "string" && ref.css) {
      const path = resolveCustomPath(ref.css, appRoot, genDir);
      if (!ref.css.startsWith("@") && !HTTP_URL.test(ref.css))
        readFileSync(resolve(appRoot, ref.css), "utf8");
      return path;
    }
    if (kind !== "styles") return resolveRef(ref, kind);
    const name = resolveName(ref, "");
    if (typeof ref !== "string" && ref.package)
      return `${ref.package}/styles/styles/style-${name}.css`;
    if (!(officialStyles as readonly string[]).includes(name))
      throw new Error(`Custom UI style "${name}" requires css or package`);
    return `@ziioapp/ui/styles/styles/style-${name}.css`;
  }
  const lines = [
    HEADER,
    '@import "@fontsource-variable/inter";',
    '@import "@ziioapp/ui/styles/shadcn.css";',
    '@import "@ziioapp/ui/styles/theme-base.css";',
  ];
  for (const kind of ["styles", "bases", "themes", "charts"] as const)
    for (const path of dedup(assets[kind].map((ref) => assetPath(ref, kind))))
      lines.push(
        `@import ${JSON.stringify(path)}${kind === "styles" ? " layer(base)" : ""};`,
      );
  for (const path of config.custom ?? [])
    lines.push(
      `@import ${JSON.stringify(resolveCustomPath(path, appRoot, genDir))};`,
    );
  lines.push('@import "@ziioapp/framework/styles/source.css";');
  return `${lines.join("\n")}\n`;
}

const MANIFEST_REL_PATH = "src/styles/theme.manifest.ts";

/** Legacy names remain strings; named custom options carry presentation metadata, never file paths. */
export function generateManifest(config: ThemeConfig): string {
  const assets = resources(config);
  const options = (refs: AssetRef[]) =>
    refs.map((ref) =>
      typeof ref === "string" || (!ref.label && !ref.group)
        ? resolveName(ref, "")
        : {
            value: ref.name,
            label: ref.label ?? ref.name,
            ...(ref.group ? { group: ref.group } : {}),
          },
    );
  const manifest = {
    defaultStyle: resolveName(config.defaults?.style, "mira"),
    styles: options(assets.styles),
    defaultTheme: resolveName(config.defaults?.theme, DEFAULT_THEME),
    defaultBase: resolveName(config.defaults?.base, DEFAULT_BASE),
    themes: options(assets.themes),
    bases: options(assets.bases),
    charts: options(assets.charts),
  };
  return `/* AUTO-GENERATED by @ziioapp/vite-plugin-theme — edit ziioapp.theme.ts instead */\nexport const themeManifest = ${JSON.stringify(manifest, null, "\t")} as const;\n`;
}

// ============================================================
// 插件
// ============================================================

export function ziioappTheme(config: ThemeConfig = {}): Plugin {
  return {
    name: "ziioapp-theme",
    configResolved(resolved) {
      const cssTarget = resolve(resolved.root, GEN_REL_PATH);
      const cssContent = generateImports(config, resolved.root);

      // 写 CSS（内容没变就不写，避免每次 dev 启动都产生 git diff）
      let cssExisting: string | null = null;
      try {
        cssExisting = readFileSync(cssTarget, "utf8");
      } catch {
        // 尚未生成
      }
      if (cssExisting !== cssContent) {
        mkdirSync(dirname(cssTarget), { recursive: true });
        writeFileSync(cssTarget, cssContent);
      }

      // 写运行时清单 theme.manifest.ts
      const manifestTarget = resolve(resolved.root, MANIFEST_REL_PATH);
      const manifestContent = generateManifest(config);
      let manifestExisting: string | null = null;
      try {
        manifestExisting = readFileSync(manifestTarget, "utf8");
      } catch {
        // 尚未生成
      }
      if (manifestExisting !== manifestContent) {
        mkdirSync(dirname(manifestTarget), { recursive: true });
        writeFileSync(manifestTarget, manifestContent);
      }
    },
  };
}
